### PR TITLE
fix: null plate value and duplicate keys message

### PR DESCRIPTION
**Pull request by solareon**
Fixes issue where fake plate configuration is enabled and the vehicle doesn't have a fake plate causing the native to fail which prevents users from getting keys/fuel/etc.

### CODE REVIEW

**Comment by Fraprwnt** [comment]
This works but the notification for getting the key is double
image

**Comment by solareon** [comment]
@Apriawanto15 This is probably due to the fakeplates resource giving you keys as well. Try and comment out the export at line 139 and see if you still get dupe keys.

**Comment by Fraprwnt** [comment]
@solareon yeah no dupe

**Comment by solareon** [comment]
Okay so I think it's just a matter of adding a second check to line 139 that if you are using fake plates that it doesn't give you the keys in the garage resource since fakeplates handles it

**Comment by solareon** [comment]
@Apriawanto15
This was due to an event in the client side assigning keys. I modified the check for this so that if you are using renewedkeys it will not fire that event.

**Comment by Fraprwnt** [comment]
thank you, I'll try it later, especially since this garage is not connected to npwd garages, I tried it yesterday. @solareon

**Pull request merged**
