### PR TITLE
Move properties to server side call

### PR DESCRIPTION
**Pull request by solareon**
Since we now use server side spawns always we can pass the properties to the SpawnVehicle command and they will come out with the right props rather than relying on the client to change the vehicle. Eliminates the need to spawn the player in the car as well. Also removed setting numberplate from the client side call as this breaks fakeplates.

### CODE REVIEW

**Comment by Randolio** [comment]
You still rely on the client to set the properties regardless?
```
RegisterNetEvent('qbx_core:client:vehicleSpawned', function(netId, props)
    local veh = NetworkGetEntityFromNetworkId(netId)
    for i = -1, 0 do
        local ped = GetPedInVehicleSeat(veh, i)
        if ped ~= cache.ped and ped > 0 and NetworkGetEntityOwner(ped) == cache.playerId then
            DeleteEntity(ped)
        end
    end
    if props then
        lib.setVehicleProperties(veh, props)
    end
end)
```

**Comment by solareon** [comment]
Yes at the core level but the core's code for spawning the vehicle with props covers all the waits before releasing the vehicle. Why redo something that the core provides?

**Comment by solareon** [comment]
@xViperAG there is one more issue with prop setting on server side spawns that should be fixed once https://github.com/Qbox-project/qbx_core/pull/317 is merged. This PR is still good though.

**Comment by solareon** [comment]
> You still rely on the client to set the properties regardless?
> 
> ```
> RegisterNetEvent('qbx_core:client:vehicleSpawned', function(netId, props)
>     local veh = NetworkGetEntityFromNetworkId(netId)
>     for i = -1, 0 do
>         local ped = GetPedInVehicleSeat(veh, i)
>         if ped ~= cache.ped and ped > 0 and NetworkGetEntityOwner(ped) == cache.playerId then
>             DeleteEntity(ped)
>         end
>     end
>     if props then
>         lib.setVehicleProperties(veh, props)
>     end
> end)
> ```

@Randolio so funny thing about this. Apparently this was the way to do it in ox_lib but that was deprecated in the code but the docs weren't updated to reflect that.

**Pull request merged**
